name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack Build Files
      run: |
        mkdir ~/buildfiles
        mv helloWorld/bin/Release/netcoreapp5.0/* ~/buildfiles
        mv graphicStuff/bin/Release/netcoreapp5.0/* ~/buildfiles
        mv guessmynumber/bin/Release/netcoreapp5.0/* ~/buildfiles
    - name: Publish Build Files
      uses: actions/upload-artifact@v2
      with:
        path: ~/buildfiles/*
        name: buildfiles
